import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useTSTranslation } from '@/hooks/useTSTranslation'

export default function Home() {
  const { t, lang } = useTSTranslation('common')

  return (
    <>
      <Head>
        <title>TypeScript on next-translate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a rel='noreferrer' target="_blank" href='https://www.linkedin.com/in/lirbre/'>{t('reach_me_at')}</a>
        <a rel='noreferrer' target="_blank" href='https://www.linkedin.com/in/lirbre/'>{t('typescript_rules')}</a>
      </main>
    </>
  )
}
